package corbaBanque;


/**
* corbaBanque/IBanqueRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Tuesday, November 18, 2025 9:50:24 PM CET
*/

public interface IBanqueRemote extends IBanqueRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IBanqueRemote
