package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Tuesday, November 18, 2025 9:50:24 PM CET
*/

public interface IBanqueRemoteOperations 
{
  void creerCompte (corbaBanque.Compte cpte);
  void verser (int code, float mt);
  void retirer (int code, float mt);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
  double conversion (float mt);
} // interface IBanqueRemoteOperations
